version: "1.0"
info:
  model: int-scaffold
packages:
- name: BE_OB_i8c_EdgeProject
  gitServerName: BE_OB_i8c_Github
  gitUrl: https://github.com/baeldos
  gitUsername: baeldos
  gitBranch: main
- name: BE_OB_i8c_GitTestPackage
  version: "1.0"
  gitServerName: BE_OB_i8c_Github
  gitUrl: https://github.com/baeldos
  gitUsername: baeldos
  gitBranch: master
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:BE_OB_Local_DB1
  packages:
  - name: BE_OB_i8c_EdgeProject
    version: "1.0"
  - name: BE_OB_i8c_GitTestPackage
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.be_ob_i8c_edge.integrations:BE_OB_i8c_Move_File_SFTP
  packages:
  - name: BE_OB_i8c_EdgeProject
    version: "1.0"
  - name: BE_OB_i8c_GitTestPackage
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: BE_OB_i8c_GitTestPackage:some_flow_service
  packages:
  - name: BE_OB_i8c_GitTestPackage
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.be_ob_i8c_edge.integrations:BE_OB_i8c_Test_Flow
  packages:
  - name: BE_OB_i8c_EdgeProject
    version: "1.0"
  - name: BE_OB_i8c_GitTestPackage
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.be_ob_i8c_edge.integrations:SaveToDB
  packages:
  - name: BE_OB_i8c_EdgeProject
    version: "1.0"
  - name: BE_OB_i8c_GitTestPackage
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.keyStore
  : ""
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.dbType
  : MySQL
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.databaseName
  : demo
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.networkProtocol
  : ""
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.password
  : "{AES}ePZNQse0Y/3ltkaXIPedVw=="
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.user
  : root
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.serverName
  : localhost
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.portNumber
  : "3306"
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionEnabled
  : "false"
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.driverType
  : mysql
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.trustStore
  : ""
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.BE_OB_i8c_EdgeProject.project.be_ob_i8c_edge.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.BE_OB_Local_DB1.connectionSettings.otherProperties
  : loginTimeout=60;
