version: "1.0"
info:
  model: int-scaffold
packages:
- name: BE_OB_i8c_EdgeProject
  gitServerName: BE_OB_i8c_Github
  gitUrl: https://github.com/baeldos
  gitUsername: baeldos
  gitBranch: main
services:
- serviceName: project.be_ob_i8c_edge.integrations:BE_OB_i8c_Move_File_SFTP
  packages:
  - name: BE_OB_i8c_EdgeProject
    version: "1.0"
